### ISSUE TITLE
TST: Travis CI Python version ignored, no test against stable Astropy

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stwcs#101]
@stsci-hack and I discovered some bugs on how `.travis.yml` is configured.

1. Do not use `python` directive, instead use `PYTHON_VERSION`. See `astropy` file as an example.
2. One of the job should be using `ASTROPY_VERSION=stable` to avoid breaking backward compatibility in your package.
3. Use `ASTROPY_VERSION=development` to pick up the dev version. There is no need to hardcode the `git` command.

**Comment by nden** [comment]
1. `python=` works fine. `PYTHON_VERSION` is fine too.
2. I don't want `ASTROPY_VERSION=stable`. I want the astropy version in astroconda.
    If there's a bug it's actually that `ASTROPY_DEV` is not picked up in any of the tests.
3. Yeah, there's nothing wrong with a hard-coded git - unless the astropy git repo address is going to change. 

Thanks for making me look closely at the actual test results.

**Comment by pllim** [comment]
Okay, feel free to close if this is not an issue.
