### ISSUE TITLE
Running updatewcs() multiple times causes problems

### ISSUE THREAD

**Issue by npirzkal** [spacetelescope/stwcs#106]
If I run updatewcs() more than once on a WFC3 FLT time, things get really confused: The first time it runs, if alters the WCS solution in a way that I can understand. But if you run updatewcs a second time, you get the same result as if not running it.

Here is an example:
Original 500 500
ra,dec and back to x,y in original: 500.00000000027416 499.9999999998585
Running updatewcs
ra,dec and back to x,y  in updatewcs(orginal): 498.6298533528224 499.43186222970786
Running updatewcs
ra,dec and back to x,y in updatewcs(updatewcs(orginal)): 499.9999999994957 499.9999999953178

**Comment by mdlpstsci** [comment]
@nden, @mrafelski and @Vb2341 of the WFC3 team were asking about the status of this issue.  Are there any updates?

**Comment by nden** [comment]
We discussed it offline and agreed it's not an issue with the current version.
@npirzkal please confirm and close the issue if you agree.

**Comment by mrafelski** [comment]
Do you know when this version will make it to astroconda? Thanks!

**Comment by npirzkal** [comment]
It was fixed when I checked out the latest master on August 28 using 
pip install git+https://github.com/spacetelescope/stwcs.git

**Comment by nden** [comment]
Thanks @npirzkal . @mrafelski  I'll push a new public release tomorrow.
