### ISSUE TITLE
Updatewcs 1.5.1 failed with new IDCTAB

### ISSUE THREAD

**Issue by samanthalh** [spacetelescope/stwcs#114]
Hello!

I was running updatewcs on some ACS images of 47 Tuc (ex. ja9bw1xhq_flc.fits) with a new IDCTAB when updatewcs crashed. I took a screenshot of the traceback to help you with debugging see attached), but you can see that it was stwcs 1.5.1 with python 3.7.3. It ran perfectly when I used version 1.4.2 of stwcs that I had in an older environment with python 3.5.6, so I know the problem is not the IDCTAB, but something to do with updatewcs. Also, this is data that was downloaded awhile ago (header says 2018-06-11) so it doesn't have the new astrometry. I'm putting the two lines of code that I used to get this error below. 

import stwcs
stwcs.updatewcs.updatewcs('j*flc.fits', use_db=False)

Please let me know if you need any other information. 

Cheers,
Samantha

![trace_from_updatewcs_crash](https://user-images.githubusercontent.com/32076878/71211676-a011d100-227d-11ea-9060-7466fb298d74.png)

**Comment by pllim** [comment]
Looks like a bug. The definition of `f` was commented out in #80 .

https://github.com/spacetelescope/stwcs/blob/04be7a617c76a98e1df321bf1c86484abcd0d696/stwcs/updatewcs/__init__.py#L410

**Comment by nden** [comment]
@samanthalh I'll be able to look at this next week.

**Comment by nden** [comment]
@samanthalh The fix is on master. Let me know if you need a released version of stwcs? I can do one this week.

**Comment by nden** [comment]
Also sorry it took so long.

**Comment by samanthalh** [comment]
Great, thanks!! And no worries, I was able to use the old version, so this didn't slow down my analysis. I think this should be released so that users don't encounter the same bug, but it can be done on whatever usual timescale you use for releases. As far as I know, it's not more pressing than any other bug fix. Thanks again!
