### ISSUE TITLE
Fix order of WCSs applied to image

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stwcs#120]
Testing of drizzled products gets complicated by the fact that the order of the WCSDVARR extensions containing the WCS solutions can change from one build to the next.  This occurs due to the use of a simple Python dict to manage the apriori solutions returned by the database.  This should be updated to use an OrderedDict instead to preserve whatever (arbitrary and still potentially volatile) order the WCSs have as returned by the astrometry database.   Comparisons with fitsdiff would then be easier to interpret.

Tracked with [JIRA HLA-290](https://jira.stsci.edu/browse/HLA-290).

**Comment by nden** [comment]
Aren't all dictionaries in Python now ordered?

Would it be better (more robust) to use the programmatic interface of `fitsdiff` and compare HDUs? 
Alternatively, there's a function in stwcs which maps WCSDVARR to FITS extension number, used internally in stwcs to update the correct WCSDVARR extension, though this approach may be not as straightforward as comparing HDUs.

**Comment by stsci-hack** [comment]
Python dictionaries only became ordered as of Python 3.7.  However, the pipeline has not yet been updated to that version, therefore, this problem arises when updating from the astrometry database.  

Furthermore, since the comparisons are done by the pipeline during testing, we have no control over how it is done or what is used.  We can suggest, but that would require the effort of another Sprint team (or more precisely, the newly formed team).  So, you are correct that there may be other ways to do the comparisons and that dictionaries as of 3.7 are all ordered, there are still operational environments where these do not apply yet.

Ultimately, making this change will not only be the simplest way to help this situation for both the Python version and the testing comparisons, but this change will be harmless even when they upgrade to 3.7 or 3.8, unless (and this always seems to be the case) I am overlooking something.  Therefore, this change seems worth doing at this time.

**Comment by nden** [comment]
We agreed this should be closed as dictionaries in Python 3.7 are ordered.
