### ISSUE TITLE
Wrong WCS being archived when applying updatewcs with use_db=True multiple times

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#129]
It looks to me that the WCS being archived after >= 2 runs of `updatewcs()` is the wrong one. This issue might be related to #128. It seems that `updatewcs()` keeps archiving AltWCS instead of the primary WCS.

To illustrate, first I deleted all WCSes except for original WCS, then I run `updatewcs(use_db=False)`, and then I run `updatewcs(use_db=True)` several times. Here is a summary of the WCSes in the header:

#### Note (Common part):
All WCSes have the following parameters in common so they will not be repeated:
```
CRPIX1  =               2048.0 / Pixel coordinate of reference point            
CRPIX2  =               1026.0 / Pixel coordinate of reference point            
CUNIT1  = 'deg'                / Units of coordinate increment and value        
CUNIT2  = 'deg'                / Units of coordinate increment and value        
CTYPE1  = 'RA---TAN-SIP'       / TAN (gnomonic) projection + SIP distortions    
CTYPE2  = 'DEC--TAN-SIP'       / TAN (gnomonic) projection + SIP distortions    
```

#### Run 0 (`updatewcs(use_db=False))`:
```
WCSNAME = 'IDC_2731450pi'      / Coordinate system title                        
CRVAL1  =       83.19300506082 / [deg] Coordinate value at reference point      
CRVAL2  =   -67.73222548108998 / [deg] Coordinate value at reference point      
CD1_1   = 3.92029060251604E-06 / partial of first axis coordinate w.r.t. x      
CD1_2   = -1.0082434475667E-05 / partial of first axis coordinate w.r.t. y      
CD2_1   = -1.0351930440257E-05 / partial of second axis coordinate w.r.t. x     
CD2_2   = -4.5644540153863E-06 / partial of second axis coordinate w.r.t. y     
```

#### Run 1 (`updatewcs(use_db=True))`:
```
WCSNAMEA= 'IDC_2731450pi'                                                       
CRVAL1A =       83.19300506082 / [deg] Coordinate value at reference point      
CRVAL2A =      -67.73222548109 / [deg] Coordinate value at reference point      
LONPOLEA=                180.0 / [deg] Native longitude of celestial pole       
LATPOLEA=      -67.73222548109 / [deg] Native latitude of celestial pole        
CD1_1A  =   3.920290602516E-06 / partial of first axis coordinate w.r.t. x      
CD1_2A  = -1.0082434475667E-05 / partial of first axis coordinate w.r.t. y      
CD2_1A  = -1.0351930440257E-05 / partial of second axis coordinate w.r.t. x     
CD2_2A  = -4.5644540153863E-06 / partial of second axis coordinate w.r.t. y     

WCSNAME = 'IDC_2731450pi-FIT_REL_GAIADR2'                                       
CRVAL1  =      83.192882353876 / [deg] Coordinate value at reference point      
CRVAL2  =     -67.732242935857 / [deg] Coordinate value at reference point      
LONPOLE =                180.0 / [deg] Native longitude of celestial pole       
LATPOLE =     -67.732242935857 / [deg] Native latitude of celestial pole        
CD1_1   =  3.9224079009662E-06 / partial of first axis coordinate w.r.t. x      
CD1_2   = -1.0086154113768E-05 / partial of first axis coordinate w.r.t. y      
CD2_1   = -1.0362353698318E-05 / partial of second axis coordinate w.r.t. x     
CD2_2   = -4.5651680786243E-06 / partial of second axis coordinate w.r.t. y     
```
WCS `'A'` has (almost) the same values as primary WCS after `updatewcs(use_db=False)` except that some values seem to be rounded (I wish this would not happen). So, everything appears to be OK.

#### Run 2 (`updatewcs(use_db=True))`:
```
WCSNAMEA= 'IDC_2731450pi'                                                       
CRVAL1A =       83.19300506082 / [deg] Coordinate value at reference point      
CRVAL2A =      -67.73222548109 / [deg] Coordinate value at reference point      
LONPOLEA=                180.0 / [deg] Native longitude of celestial pole       
LATPOLEA=      -67.73222548109 / [deg] Native latitude of celestial pole        
CD1_1A  =   3.920290602516E-06 / partial of first axis coordinate w.r.t. x      
CD1_2A  = -1.0082434475667E-05 / partial of first axis coordinate w.r.t. y      
CD2_1A  = -1.0351930440257E-05 / partial of second axis coordinate w.r.t. x     
CD2_2A  = -4.5644540153863E-06 / partial of second axis coordinate w.r.t. y     

WCSNAMEB= 'ie6d07ujq_flt_IDC_2731450pi-FIT_REL_GAIADR2'                         
CRVAL1B =       83.19300506082 / [deg] Coordinate value at reference point      
CRVAL2B =      -67.73222548109 / [deg] Coordinate value at reference point      
LONPOLEB=                180.0 / [deg] Native longitude of celestial pole       
LATPOLEB=      -67.73222548109 / [deg] Native latitude of celestial pole        
CD1_1B  =   3.920290602516E-06 / partial of first axis coordinate w.r.t. x      
CD1_2B  = -1.0082434475667E-05 / partial of first axis coordinate w.r.t. y      
CD2_1B  = -1.0351930440257E-05 / partial of second axis coordinate w.r.t. x     
CD2_2B  = -4.5644540153863E-06 / partial of second axis coordinate w.r.t. y     

WCSNAME = 'IDC_2731450pi-FIT_REL_GAIADR2'                                       
CRVAL1  =      83.192882353876 / [deg] Coordinate value at reference point      
CRVAL2  =     -67.732242935857 / [deg] Coordinate value at reference point      
LONPOLE =                180.0 / [deg] Native longitude of celestial pole       
LATPOLE =     -67.732242935857 / [deg] Native latitude of celestial pole        
CD1_1   =  3.9224079009662E-06 / partial of first axis coordinate w.r.t. x      
CD1_2   = -1.0086154113768E-05 / partial of first axis coordinate w.r.t. y      
CD2_1   = -1.0362353698318E-05 / partial of second axis coordinate w.r.t. x     
CD2_2   = -4.5651680786243E-06 / partial of second axis coordinate w.r.t. y     
```

WCS `'B'` is a copy of the WCS `'A'` instead of the primary WCS. Subsequent runs of `updatewcs(use_db=True)` keep making copies of WCS `'B'` instead of the primary WCS.

First of all, I think there should be detection if a WCS was already archived, no new copies should be created. Secondly, it seems that the wrong WCS is archived: instead of archiving the primary WCS, `updatewcs` archives an alternate WCS! This does not seem right.

CC: @stsci-hack @nden

**Comment by nden** [comment]
I think this is by design. However, I am not sure it's correct either. It works like this:

- First run
  - Run updatewcs using the distortion files and create a Primary WCS.
     `WCSNAME` is set to `IDC_<idcfile_rootname>`.
  - Get the best solution from the database. Compare it WCSNAME with the WCSNAME of the Primary one. 
     If different continue (see below why they are always different)
  - Archive the Primary WCS (wcskey=A)
  - Replace the Primary WCS with the one from the database. 
     `WCSNAME` is set to the WCSNAME of the database solution which follows a different pattern.
  - Update the distortion files with the ones used by the database solution
- Second run
  1. Run updatewcs using the distortion files (the new ones) and create a Primary WCS. 
     **This will use the name of the new idcfile to create a WCSNAME using the pattern `IDC_<idcfile_rootname>`.**
  2. Get the best solution from the database (note that it is the same one as before)
  3. Archive the Primary WCS (from distortion files, wcskey=B)
  4. Compare the best solution WCSNAME with the current WCSNAME of the Primary WCS.
    Although it's the same solution the wcsnames are different because of i) above
  5.  Replace the Primary WCS with the one from the database 
  6. Update the distortion files with the ones used by the database solution

and so on ...

**Comment by mcara** [comment]
Inserting a verification that the `wname` is unique (not already an alt WCS) before https://github.com/spacetelescope/stwcs/blob/9525b08204d4493cfc71069b5e9a521c1476b5e9/stwcs/wcsutil/altwcs.py#L152 and returning without archiving if it s seems to solve the issue.

**Comment by nden** [comment]
This can now be closed?

**Comment by mcara** [comment]
Yes
