### ISSUE TITLE
Strange code in altwcs

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#130]
There is a very strange line of code in `stwcs.wcsutil.altwcs.py`:

https://github.com/spacetelescope/stwcs/blob/cb361e6e1b9cd64c4ce9e4dc032713fc9a034b2e/stwcs/wcsutil/altwcs.py#L121

It is a loop that loops only over the last element:

```python
>>> for k in ['a', 'b', 'c'][-1::]:
>>>    print(k)
c
```

CC: @stsci-hack @nden

**Comment by mcara** [comment]
Git blame (if it helps understand the context):

https://github.com/spacetelescope/stwcs/commit/0f3e78c160bd407e37ee1b094140b88fe6b8022b

**Comment by mcara** [comment]
I think this code was intended to pick a `wcsname` for the WCS to be archived based on the last archived WCS when user did not provide `wcsname` or when the primary WCS does not have a name.

I'll make a PR to fix the code which also has another bug at https://github.com/spacetelescope/stwcs/blob/cb361e6e1b9cd64c4ce9e4dc032713fc9a034b2e/stwcs/wcsutil/altwcs.py#L123

`wnames` is a dictionary while `wname` should be a string.

**Comment by nden** [comment]
@mcara I doubt that was the intention because ... why? Perhaps it was only meant to create a default name.

**Comment by mcara** [comment]
Hm, if only creating a default name, why even use a loop with IF?

**Comment by mcara** [comment]
@stsci-hack Could you please take a look at this?

**Comment by stsci-hack** [comment]
Best guess:  a clumsy attempt to loop over the WCSNAMES in reverse order with the intended syntax most likely supposed to be 'a[::-1]'.  It mostly worked since it pulled and checked the last key which was most often the desired default WCS since it was the last one archived.  So, feel free to revise or remove as needed.

**Comment by mcara** [comment]
I believe https://github.com/spacetelescope/stwcs/pull/134/files#diff-516dcd10bb4c104d97362626d506e981R127 does exactly that:
```python
wname = sorted(wnames.items(), key=lambda x: x[0])[-1][1]
```
Sort dictionary by keys and pick the value of the last key.
