### ISSUE TITLE
_restore() overwrites archived WCS CTYPE

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#133]
I think this code has the opposite effect of what is desired:

https://github.com/spacetelescope/stwcs/blob/d190f7b0b1a526f6eb7568f4caa4e45a6613395e/stwcs/wcsutil/altwcs.py#L447-L448

CC: @nden

**Comment by nden** [comment]
Alternate WCSs do not change the distortion, so they all have the same `CTYPE` (except may be the original OPUS one. The proposed refactor is better, I'm just saying that there are no bad files as a result of this code.

**Comment by mcara** [comment]
> I'm just saying that there are no bad files as a result of this code

Probably. I was not sure about OPUS and its effect. Like what happens the first time the code is run.

**Comment by mcara** [comment]
I mean,... since AltWCS do not change distortion, it appears this code would not be necessary at all. But it was there and I suspecting it was for a reason. My guess was that the reason might be to preserve CTYPE just in case if it is ever necessary (I do not know if it ever happens) but then it is clear that this code was working in the opposite direction.
