### ISSUE TITLE
When restoring from altwcs 'O', TDDALPHA is not reset

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#140]
Code https://github.com/spacetelescope/stwcs/blob/0e985fb0dc9280b1aea6d5b26c42d42f8788507a/stwcs/wcsutil/altwcs.py#L456-L458

is never really executed unless one of WCS keywords starts with `'O'` and has length 2 and it is the last keyword in the previous loop. This is because `key` is a loop variable in the loop before this code.

What I do not know is what would be the consequences of this bug. Maybe it is harmless.

CC: @nden

**Comment by nden** [comment]
YEs, this is a bug, it should be `ukey`, not `key`. I don't think there will be any real consequences of this but it should be fixed, of course.
