### ISSUE TITLE
Should updatewcs overwrite OPUS WCS?

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#145]
Looking at https://github.com/spacetelescope/stwcs/blob/9525b08204d4493cfc71069b5e9a521c1476b5e9/stwcs/updatewcs/__init__.py#L188-L190
the code, at first glance seems harmless: backup something that was previously "restored" even if this is inefficient. However,  `restoreWCS` does not fail if `'OPUS'` WCS is not present in the image header at the time `updatewcs()` is run and this results in creating an `'OPUS'` WCS from the primary WCS (whatever that might be).

Is this desired behavior or is it just acceptable or should we remove this code?

CC: @stsci-hack @nden

**Comment by stsci-hack** [comment]
Data being processed in the calibration pipeline starts out with a WCS defined purely from a static definition of the detector aperture position and a minimal, typically outdated, linear distortion model that does not rely on distortion model calibration files.  This WCS, however, provides the most direct computation of the relative alignment of chips in each detector's observation as well as the most accurately known (although occassionally faulty) relative alignment of observations in an association and within a visit.  The primary task of 'updatewcs' is to preserve this WCS as the basis for recomputing any new WCS based on distortion calibration files, and this line of code (if I remember correctly, and based on your description) is the code that defines how this WCS gets preserved as the alternate WCS named 'OPUS'.  All subsequent re-computations based on distortion model calibration reference files would actually fail is this alternate WCS does not get defined.

**Comment by mcara** [comment]
Thank you! Then, if I understand this correctly, only on the very first run of `updatewcs` `'OPUS'` Alt WCS is created and on all other runs it just gets overwritten by itself.

**Comment by nden** [comment]
That is correct. We can probably not archive if it already exists. However, we need to restore every time before we run makecorr.
