### ISSUE TITLE
Should WCSNAME* be case-insensitive?

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#146]
Current code in https://github.com/spacetelescope/stwcs/blob/9525b08204d4493cfc71069b5e9a521c1476b5e9/stwcs/wcsutil/altwcs.py#L707 seems to be case-insensitive. I just want to double check that this is the desired behavior for the `WCSNAME`.

CC: @stsci-hack @nden

**Comment by nden** [comment]
Like all FITS keywords.

**Comment by mcara** [comment]
> Like all FITS keywords.

No, this is different. This is not about `wcsname` being the same as `WCSNAME` but rather:

**Comment by mcara** [comment]
In other words, if we want to have only a single Alt WCS with a given WCSNAME, should the following be allowed or not:
```
WCSNAMEA=Some Name
WCSNAMEB=SOME NAME
WCSNAMEC=some name
```
?

**Comment by nden** [comment]
Oh, you are asking about the value. There's no convention.

**Comment by mcara** [comment]
Current code treats WCSNAME values as case-insensitive for the purpose of identifying corresponding WCS keys. Should is this how we want to have WCS names be when they are compared?

**Comment by mcara** [comment]
> There's no convention.

This suggests that the comparison should not be case-insensitive, i.e., `name1` should be considered distinct from `NAME1`, right?

**Comment by stsci-hack** [comment]
Treating WCSNAME values as case-insensitive makes it easier for the user to see that there are differences in the WCSs.  It would be immensely confusing (as if it isn't already confusing enough) to explain to a user why a WCS named 'IDC_a123458bq-hsc30' is not the same as 'IDC_a123458bq-HSC30' since both reference 'HSC30'.  Besides, users are already used to FITS keywords being case-insensitive, so simplifying the treatment of alternate WCSs by making them case-insensitive seems to be consistent with FITS.  Therefore, it would be the most user-friendly, in my opinion, to keep WCSNAME as case-insensitive.

**Comment by mcara** [comment]
But why would our software sometimes write `'IDC_a123458bq-hsc30'` and sometimes `'IDC_a123458bq-HSC30'`? I think the solution to this question now should be based on whether our existing software mixes cases when writing WCS names.

**Comment by stsci-hack** [comment]
I would not want to try to second-guess how these situations arise.  However, users can provide a list of catalog names as an input parameter to the alignment code which would then get used to generate these names.  If they provided lower-case one time and upper-case another (interactively, without thinking), they would end up with mixed cases as separate WCSs even though they may be identical.  So, there are ways in which the user can cause this situation and make having WCSNAME be treated as case-insensitive be useful.

**Comment by mcara** [comment]
Thanks!

**Comment by mcara** [comment]
@stsci-hack But then there is code that is case sensitive, like here:
https://github.com/spacetelescope/stwcs/blob/4a574760c0c2a9f943541a668dd3244930716074/stwcs/wcsutil/wcscorr.py#L311-L315

It just seems that there is inconsistency in treating WCS names.
