### ISSUE TITLE
Applying a headerlet should remove all alternate WCSs if distortions are different

### ISSUE THREAD

**Issue by nden** [spacetelescope/stwcs#160]
When a headerlet from the astrometry database is applied to an observation and its distortion is different from the one in the header the primary WCS is archived as alternate which essentially links it to the new distortion. This is incorrect. All alternate WCSs should be removed (possibly attached as headerlets) when a different distortion model is applied.

@stsci-hack Should the fix go in 1.6 or 1.7?

**Comment by stsci-hack** [comment]
This fix can go in 1.7.  The current set of distortion model reference files has been stable this year and will remain stable until we complete the reprocessing of all data once this build gets installed.  This provides us with a window to fix this issue in 1.7 and deliver it for the following round of reprocessing.
