### ISSUE TITLE
Compute new a priori WCS for updated IDCTAB in updatewcs

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stwcs#169]
The distortion models get updated as calibrations of the detectors improves.  These updates come in the form of new IDCTAB, NPOLFILE and D2IMFILE reference files.  The guide star webservice contains the offsets used to correct the original pointing of the observation to be closer to the ICRS (GAIA) reference frame and these were used to compute the original corrected _a priori_ WCS solutions stored in the astrometry database.  However, as new IDCTABs are released, new  _a priori_ WCS solutions need to be computed for the new IDCTAB while using the same offsets used for previous solutions.  These new solutions then need to be written out as headerlets so that they can be used to update the astrometry database for subsequent reprocessing or manual processing by end users.   These new WCSs need to be computed automatically when updatewcs gets called with 'use_db=True' so that the end user will always get a WCS based on the IDCTAB specified in the file's header.

Unfortunately, over time, computing these new solutions will result in an ungainly number of new WCS solutions for each exposure.  So, in addition to computing the new solution, updatewcs also needs to be updated only append solutions from the astrometry database based on the same IDCTAB as the one specified in the file header.  This will limit the number of WCSs added to the images file as extra extensions.  However, a new parameter must also be added to allow the end user to get ALL solutions from the database if desired.

**Comment by mcara** [comment]
Does this need an changelog entry?
