### ISSUE TITLE
wcskey not properly propagated in tweakback?

### ISSUE THREAD

**Issue by mtakahiro** [spacetelescope/stwcs#178]
Hi, I may need some help with tweakback to flt images that go into drz file.

I recently installed a new version of packages around drizzlepac, including drizzlepac (3.2.0) and stwcs (1.6.1). I was trying to align drizzled image (F606W_drz.fits) to a reference coordinate system (here GAIA_DR2) and then propagate the shift to the _flc.fits images that go into F606W_drz.fits through tweakback. However, the updated _flc.fits files seem to have wrong WCS parameters even though the primary wcsname is correctly set to what I wanted (wcsname="GAIA_DR2").

I sneaked a little bit and found that two modules in wcsutil.altwcs seemed to return results that are twisted as below:
```
drzfile = 'F606W_drz.fits'
wkeys = wcsutil.altwcs.wcskeys(drzfile, ext=sciext)
wnames = wcsutil.altwcs.wcsnames(drzfile, ext=sciext)
print(wkeys)
print(wnames)

[' ', 'A']
{'A': 'TWEAK2', ' ': 'GAIA_DR2'}
```
where I was rather expecting
```
[ 'A', ' ']
{'A': 'TWEAK2', ' ': 'GAIA_DR2'}
```
("TWEAK2" is the wcsname for _flc and drz.fits before tweakreg to Gaia frame).

This does not happen when I repeat the same process to get _drz.fits but with older versions of those packages (e.g. drizzlepac 3.1.6 and stwcs 1.5.3), though I get some additional elements in these arrays:
```
[' ', 'O', 'A', 'B']
{' ': 'GAIA_DR2', 'O': 'OPUS', 'A': 'TWEAK2', 'B': 'GAIA_DR2'}
```

Also, because the wkeys array has 'A' at its last element, this would cause an issue when tweakback without specifying "new wcsname" keyword (as by default it refers to wkeys[-1]), due to duplication in wcs keyword.

While this may be caused by drizzlepac rather than stwcs I wanted to bring this up here to see if anyone saw this before or knows how to handle this. 

Thanks in advance for your help. Let me know if you need any other details.

**Comment by nden** [comment]
I'm sorry this issue did not get attention. Hopefully it got reported through the help desk and resolved. Given how old it is I am closing it but please reopen if it's still a problem.
