### ISSUE TITLE
Remove SIP from headers when loading alternative WCS

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stwcs#25]
Drizzlepac logs often contain numerous messages about inconsistent use of SIP in HST images, see, e.g., https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=40222839 such as:
```
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
```
Often this happens when ``drizzlepac`` code attempts to load the "original" WCS (the one that relies on ``IDCTAB`` instead of ``SIP`` to describe distortions). ``stwcs`` should be modified to remove SIP from image headers before loading alternative WCS.

**Comment by mcara** [comment]
NOTE: these messages started with PR https://github.com/astropy/astropy/pull/4814 and in https://github.com/astropy/astropy/issues/5801 I propose that these messages be removed. Until then, ``stwcs`` should implement a workaround to suppress these messages.

CC: @stsci-hack

**Comment by nden** [comment]
I suggest we catch warning instead of deleting keywords. There was a previous PR which did this for some functions. It's either not working correctly or I missed a case. @mcara Could you point me to a log where you see the info messages?

Also I wonder if the data files should be updated. Alternate WCSs are supposed to have the same distortion model as the primary one, i.e. the distortion model applies to all WCSs in a header. A different distortion model is represented by a headerlet. Again it would help if you link to a test which issues the log message.

**Comment by mcara** [comment]
@nden As an example, see wfpc2/waiver_fits tests (link provided in the first message in this issue). It is true that some input files need to be updated, specifically, *only*  ``stis_*`` tests need to be updated and I wrote a script that I sent to @jhunkeler to run on test machines that will fix those files.

With regard to quieting logging instead of taking care of the root cause of the problem: I do not like this approach as it may quiet (in principle) other possibly valid messages. Instead, I prefer to remove important header keywords which results in:
* Not creating a WCS with ``.sip`` (i.e., ``.sip`` is ``None``)
* Not emitting that long info message from https://github.com/astropy/astropy/pull/4814
* Allows any other valid message to be outputted
* It also suppresses the ```WARNING: Some non-standard WCS keywords were excluded: B_2_1, A_1_1, A_1_2, B_ORDER, B_2_0, A_3_0, A_0_2, A_0_3, B_3_0, B_1_1, A_2_0, A_ORDER, A_2_1, B_1_2, B_0_3, B_0_2 Use the ``relax`` kwarg to control this. [astropy.wcs.wcs]``` message (also see https://github.com/spacetelescope/drizzlepac/issues/18) without blocking warning messages using this tricks like these: https://github.com/spacetelescope/stwcs/blob/master/stwcs/wcsutil/altwcs.py#L436 or https://github.com/spacetelescope/stwcs/blob/master/stwcs/wcsutil/altwcs.py#L521 which, actually do not work at all as the logging level should have been set to ``'ERROR'`` to surpres warning messages.
