### ISSUE TITLE
Add interface to astrometry database for new solutions

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stwcs#38]
This issue will be used to track the implementation of an interface to a new astrometry database which will contain new astrometrically-accurate solutions for the pointing for HST observations. 

The initial requirements for this interface will be:
- it will use a web-interface to query the database and retrieve any new WCS solutions available as headerlets for the exposure
- if access to the web-interface can not be established, the user will be notified, either through an Exception that stops all processing or a warning in the log which allows processing to continue unhindered 
- the code will rely on an environment variable to determine whether failure to access or failure in applying the new solutions will result in Exceptions (as requested by the pipeline) or simple warnings (which will support users better)
- new solutions retrieved as headerlets from the database will simply be appended to the observation
- this update will be implemented (at least initially) as part of the updatewcs step

**Comment by nden** [comment]
@stsci-hack Can this be closed?
