### ISSUE TITLE
altwcs bug, crashes AstroDrizzle

### ISSUE THREAD

**Issue by Vb2341** [spacetelescope/stwcs#4]
When running AstroDrizzle, it crashes crashes at line 353 of altwcs.py saying it can't find keyword 'MJD-OBS', which is not a header keyword, but I believe one of the WCS keywords.  

Starting in line 347 in altwcs.py:
```
    for i in ext:
        hdr = fobj[i].header
        hwcs = readAltWCS(fobj,i,wcskey=wkey)
        if hwcs is None:
            continue
        for k in hwcs:
            del hdr[k]
```

Drizzle runs fine if those lines are changed to:
```
    for i in ext:
        hdr = fobj[i].header
        hwcs = readAltWCS(fobj,i,wcskey=wkey)
        if hwcs is None:
            continue
        for k in hwcs.keys():
            del hwcs[k]
```

EDIT:  After looking at the code more, I see that this does not 'fix' the behavior, rather just avoids a currently broken behavior.

It seems that hwcs somehow gets extra keys that are not part of the hdr object.  Perhaps readAltWCS is getting more keywords somehow?

**Comment by nden** [comment]
@Vb2341 What version of python are you using?

**Comment by Vb2341** [comment]
I'm using Python 2.7.

**Comment by nden** [comment]
@Vb2341 This is valid Python 2.7 code. Could you post the astrodrizzle error? If the traceback is too long, you can copy it to a gist.

**Comment by Vb2341** [comment]
https://gist.github.com/Vb2341/8cb6e769d16d6919abce8e1050704b13

It appears this bug only occurs after a new WCS has been created via something like TweakReg and Drizzled afterwards.

**Comment by nden** [comment]
@Vb2341 Thanks for reporting this. It whould be fixed on master now.
