### ISSUE TITLE
update readthedocs account to point to master branch

### ISSUE THREAD

**Issue by nden** [spacetelescope/stwcs#43]
and fix doc build.

@justincely It appears you are the only owner of this account. Can you add me as a maintainer?

**Comment by justincely** [comment]
sure - what's your readthedocs handle?  Looks like I'm the sole maintainer on a few other repos too.  I'll transfer as many as i see to you (or whomever you'd like me to)

**Comment by nden** [comment]
"nadia.dencheva" is my handle. You can pass all of them to me and we'll take it from there. Thanks for the quick response.

**Comment by nden** [comment]
@justincely Any chance adding me as a maintainer?

**Comment by justincely** [comment]
Sorry, got lost in the shuffle - you're now maintainer to any project where
I had been the sole maintainer.  Enjoy!

**Comment by nden** [comment]
Thanks!
