### ISSUE TITLE
TST: Port and deactivate pandokia tests

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stwcs#52]
Currently, tests are still running in pandokia using the following files, separate from those in this repo (xref https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=10553):

* testaltwcs.py
* testheaderlet.py
* test.py

However, I also see legit tests in the `tests` sub-directory in this repo. Why can't we just ~~activate Travis CI here and~~ deactivate those in pandokia? These tests don't see data intensive, so I don't even think we need Jenkins and Artifactory here.

**Comment by pllim** [comment]
Update: Wait a minute, there *is* a https://travis-ci.org/spacetelescope/stwcs/ . So, why is it still running tests in pandokia?

**Comment by nden** [comment]
Yes, the pandokia tests can be disabled.

**Comment by pllim** [comment]
Well, that's easy! Thanks!
