### ISSUE TITLE
headerlet restore function fails

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stwcs#59]
Use of the `restore_from_headerlet()` function results in an Exception being thrown as it tries to identify what extension needs to be updated in the science file.  The exact call and Exception is given below. 

This error needs to be corrected in order to allow users to successfully choose what WCS they want to use after updating with astrometrically-corrected solutions from the astrometry database (for example).

`In [57]: headerlet.restore_from_headerlet(m35names[0], hdrname='ic4001vjq_IDC_yas1621ai-GSC-GAIAdr1', force=True)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-57-6c6e1d147801> in <module>()
----> 1 headerlet.restore_from_headerlet(m35names[0], hdrname='ic4001vjq_IDC_yas1621ai-GSC-GAIAdr1', force=True)

/user/hack/dev/release/anaconda3/envs/hstrt-2018.1a/lib/python3.6/site-packages/stwcs/wcsutil/headerlet.py in wrapped(*args, **kw)
    128 
    129         init_logging(func.__name__, level, mode, **func_args)
--> 130         return func(*args, **kw)
    131     return wrapped
    132 

/user/hack/dev/release/anaconda3/envs/hstrt-2018.1a/lib/python3.6/site-packages/stwcs/wcsutil/headerlet.py in restore_from_headerlet(filename, hdrname, hdrext, archive, force, logging, logmode)
   1485         if 'extname' in ext.header and ext.header['extname'] == 'SIPWCS':
   1486             # convert from string to tuple or int
-> 1487             sciext = eval(ext.header['sciext'])
   1488             extlist.append(fobj[sciext])
   1489     # determine whether distortion is the same

/user/hack/dev/release/anaconda3/envs/hstrt-2018.1a/lib/python3.6/site-packages/astropy/io/fits/header.py in __getitem__(self, key)
    143         else:
    144             keyword = key
--> 145         card = self._cards[self._cardindex(key)]
    146         if card.field_specifier is not None and keyword == card.rawkeyword:
    147             # This is RVKC; if only the top-level keyword was specified return

/user/hack/dev/release/anaconda3/envs/hstrt-2018.1a/lib/python3.6/site-packages/astropy/io/fits/header.py in _cardindex(self, key)
   1652 
   1653         if not indices:
-> 1654             raise KeyError("Keyword {!r} not found.".format(keyword))
   1655 
   1656         try:

KeyError: "Keyword 'SCIEXT' not found."
`

**Comment by nden** [comment]
fixed in #60
