### ISSUE TITLE
AstrometryDB inaccessible

### ISSUE THREAD

**Issue by dkmagee** [spacetelescope/stwcs#61]
Is there a public access point for the AstrometryDB service? The default URL appears to point to a development server that it is not accessible outside of STScI. 

`from stwcs.updatewcs import astrometry_utils as stwcsau`
`db = stwcsau.AstrometryDB()`
`WARNING : AstrometryDB service inaccessible!`
`    AstrometryDB called: https://mastdev.stsci.edu/portal/astrometryDB/`

**Comment by stsci-hack** [comment]
This code relies on a database to provide updated WCS solutions for exposures.  That database, unfortunately, has taken a LOT longer to populate and verify with an initial set of new solutions than originally planned.  Work is currently underway to generate new solutions, verify them, and define the new database.  This work, however, will not result in a publicly accessible database until September 2018 at the earliest at which time this default URL will be updated to point to the new public interface signifying when it will be available for all to use.

**Comment by stsci-hack** [comment]
This code relies on a database to provide updated WCS solutions for exposures.  That database, unfortunately, has taken a LOT longer to populate and verify with an initial set of new solutions than originally planned.  Work is currently underway to generate new solutions, verify them, and define the new database.  This work, however, will not result in a publicly accessible database until September 2018 at the earliest at which time this default URL will be updated to point to the new public interface signifying when it will be available for all to use.
