### ISSUE TITLE
updatewcs attempts to write to astrometry database

### ISSUE THREAD

**Issue by nden** [spacetelescope/stwcs#76]
Currently the flow in `updatewcs` is:

- run updatewcs and populated the WCS based on eference files and distortion
- check for better WCS solutions for this file in the apriori astrometry database
  - if available - update the WCS with it, saving the computed one as an alternate WCS.
  - if not available attempt to injst the computed WCS in the astrometry database.

Consider splitting the functionality and not updating the database by default.

**Comment by nden** [comment]
@stsci-hack

**Comment by stsci-hack** [comment]
The code was modified to remove the update step for the database.  The only update that gets performed now occur when external code creates a headerlet for a specific WCS solution from this image and that headerlet gets identified by the pipeline for ingest.  Therefore, this issue has been fully addressed.
