### ISSUE TITLE
Astrometry DB/headerlet example usage docs

### ISSUE THREAD

**Issue by Vb2341** [spacetelescope/stwcs#88]
The WFC3 team does not want to have the astrometric updates pushed into the pipeline without accompanying documentation.  Since the a posteriori astrometry isn't going live with the build, this probably doesn't need to be anything exhaustive.  It should, however show users how to switch between solutions, or at the very least, just restore the regular solution (the IDC_XXXXXXXX solution).  It should probably describe (or link to) how the a priori solution is different than the current solution.  A brief description of headerlets (the purpose of them, rather than the technical details) would likely be helpful as well.

@rjavila Does the ACS team have any thoughts on this?

**Comment by nden** [comment]
@stsci-hack

**Comment by stsci-hack** [comment]
Work has already been identified to document the new WCS solutions, both those returned by the astrometry database (a priori solutions) as well as those which get computed in the pipeline (a posteriori solutions).  This documentation was originally planned to be generated as part of the Drizzlepac documentation, however, the STWCS documentation should also be updated as part of that effort.  

We (@stsci-hack , @mdlpstsci, @dulude) planned on working with both the ACS team and the WFC3 team to make sure that what gets included in the new documentation covers all the issues which affect the science use of the new WCS solutions while also being done in a manner that is easily understandable and usable by the typical end user.  This documentation effort will start within a couple of weeks (maybe earlier), with an initial version as approved by the INS teams in place on readthedocs (at least) prior to this new capability being used to create new HST archive products.

**Comment by nden** [comment]
Given the date on this ticket and all the work that went into documentation, I'm assuming this was done and closing. Please reopen if that's not the case
