### ISSUE TITLE
TDD correction for ACS needs to be revised

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stwcs#99]
Recent testing of the ACS distortion model by the ACS INS team uncovered a problem with the TDD correction.  It appears that the correction is being applied with the wrong sign to the coefficient.  This only came to light after they gained the ability to process several hundred datasets that span a 10 year observing period.

**Comment by nden** [comment]
@stsci-hack Is this a confirmed issue?

**Comment by stsci-hack** [comment]
This issue did not require any further code changes based on feedback from INS.
